import type { JobListing } from "./types"

export const jobListings: JobListing[] = [
  {
    id: "job1",
    title: "Senior Frontend Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "full-time",
    experience: "3-5 years",
    salary: "$120k - $150k",
    postedDate: "2 days ago",
    isRemote: true,
    isFeatured: true,
    isRecent: true,
    shortDescription: "Join our team to build cutting-edge web applications using React, TypeScript, and Next.js.",
    description:
      "We are looking for a Senior Frontend Developer to join our growing team. You will be responsible for building and maintaining high-quality web applications, collaborating with cross-functional teams, and mentoring junior developers.",
    responsibilities: [
      "Develop and maintain high-quality web applications using React, TypeScript, and Next.js",
      "Collaborate with designers, product managers, and backend developers",
      "Write clean, maintainable, and efficient code",
      "Implement responsive designs and ensure cross-browser compatibility",
      "Participate in code reviews and mentor junior developers",
    ],
    requirements: [
      "3-5 years of experience in frontend development",
      "Strong proficiency in React, TypeScript, and Next.js",
      "Experience with state management libraries (Redux, Zustand, etc.)",
      "Knowledge of modern frontend build tools and workflows",
      "Understanding of web accessibility standards",
      "Excellent problem-solving and communication skills",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Flexible work arrangements",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development budget",
      "Unlimited PTO",
    ],
    industry: "Technology",
    companyDescription:
      "TechCorp is a leading technology company specializing in innovative software solutions for businesses of all sizes.",
    companySize: "501-1000 employees",
    founded: "2010",
    website: "www.techcorp.com",
  },
  {
    id: "job2",
    title: "UX/UI Designer",
    company: "DesignHub",
    location: "New York, NY",
    type: "full-time",
    experience: "2-4 years",
    salary: "$90k - $120k",
    postedDate: "1 week ago",
    isRemote: true,
    isFeatured: false,
    isRecent: true,
    shortDescription: "Create beautiful and intuitive user experiences for our digital products.",
    description:
      "We are seeking a talented UX/UI Designer to join our creative team. You will be responsible for designing user-centered interfaces for our digital products, conducting user research, and collaborating with developers to implement your designs.",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Collaborate with product managers and developers",
      "Design intuitive and accessible user interfaces",
      "Maintain and evolve our design system",
    ],
    requirements: [
      "2-4 years of experience in UX/UI design",
      "Proficiency in design tools such as Figma, Sketch, or Adobe XD",
      "Portfolio demonstrating strong visual design skills",
      "Understanding of user-centered design principles",
      "Experience with design systems",
      "Excellent communication and collaboration skills",
    ],
    benefits: [
      "Competitive salary",
      "Remote work options",
      "Health insurance",
      "Creative environment",
      "Professional development opportunities",
      "Flexible working hours",
    ],
    industry: "Design",
    companyDescription:
      "DesignHub is a creative agency that specializes in digital product design and branding for startups and established companies.",
    companySize: "51-200 employees",
    founded: "2015",
    website: "www.designhub.co",
  },
  {
    id: "job3",
    title: "Full Stack Developer",
    company: "WebSolutions",
    location: "Austin, TX",
    type: "full-time",
    experience: "3+ years",
    salary: "$100k - $130k",
    postedDate: "3 days ago",
    isRemote: false,
    isFeatured: true,
    isRecent: true,
    shortDescription: "Build robust web applications using modern technologies across the full stack.",
    description:
      "We are looking for a Full Stack Developer to join our engineering team. You will be responsible for developing and maintaining web applications, working on both frontend and backend components, and collaborating with cross-functional teams.",
    responsibilities: [
      "Develop and maintain web applications using modern JavaScript frameworks",
      "Work with backend technologies such as Node.js, Express, and MongoDB",
      "Implement responsive designs and ensure cross-browser compatibility",
      "Write clean, maintainable, and efficient code",
      "Collaborate with designers, product managers, and other developers",
    ],
    requirements: [
      "3+ years of experience in full stack development",
      "Strong proficiency in JavaScript/TypeScript",
      "Experience with React, Angular, or Vue.js",
      "Experience with Node.js and Express",
      "Knowledge of database systems (SQL and NoSQL)",
      "Understanding of RESTful APIs and microservices architecture",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Flexible working hours",
      "Professional development budget",
      "Company events and team building activities",
    ],
    industry: "Technology",
    companyDescription:
      "WebSolutions is a web development agency that specializes in building custom web applications for businesses across various industries.",
    companySize: "51-200 employees",
    founded: "2012",
    website: "www.websolutions.io",
  },
  {
    id: "job4",
    title: "Product Manager",
    company: "InnovateCo",
    location: "Seattle, WA",
    type: "full-time",
    experience: "4-6 years",
    salary: "$130k - $160k",
    postedDate: "5 days ago",
    isRemote: true,
    isFeatured: false,
    isRecent: true,
    shortDescription: "Lead product development initiatives and drive innovation for our SaaS platform.",
    description:
      "We are seeking an experienced Product Manager to join our team. You will be responsible for defining product strategy, gathering and prioritizing requirements, and working closely with engineering, design, and marketing teams to deliver successful products.",
    responsibilities: [
      "Define product vision, strategy, and roadmap",
      "Gather and prioritize product requirements",
      "Work closely with engineering, design, and marketing teams",
      "Conduct market research and competitive analysis",
      "Analyze product metrics and user feedback",
      "Present product plans to stakeholders and executives",
    ],
    requirements: [
      "4-6 years of experience in product management",
      "Experience with SaaS products",
      "Strong analytical and problem-solving skills",
      "Excellent communication and presentation skills",
      "Understanding of software development processes",
      "Experience with agile methodologies",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Remote work options",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development budget",
      "Flexible working hours",
    ],
    industry: "Technology",
    companyDescription:
      "InnovateCo is a leading SaaS company that provides innovative solutions for businesses to streamline their operations and improve productivity.",
    companySize: "201-500 employees",
    founded: "2011",
    website: "www.innovateco.com",
  },
  {
    id: "job5",
    title: "Data Scientist",
    company: "DataInsights",
    location: "Boston, MA",
    type: "full-time",
    experience: "3-5 years",
    salary: "$110k - $140k",
    postedDate: "1 week ago",
    isRemote: true,
    isFeatured: true,
    isRecent: false,
    shortDescription: "Apply machine learning and statistical techniques to extract insights from complex datasets.",
    description:
      "We are looking for a Data Scientist to join our analytics team. You will be responsible for developing and implementing machine learning models, analyzing complex datasets, and communicating insights to stakeholders.",
    responsibilities: [
      "Develop and implement machine learning models",
      "Analyze complex datasets to extract insights",
      "Collaborate with engineering and product teams",
      "Communicate findings to stakeholders",
      "Stay up-to-date with the latest developments in data science",
      "Contribute to the development of our data science platform",
    ],
    requirements: [
      "3-5 years of experience in data science",
      "Strong programming skills in Python or R",
      "Experience with machine learning libraries (scikit-learn, TensorFlow, PyTorch)",
      "Knowledge of statistical analysis and modeling",
      "Experience with data visualization tools",
      "Excellent problem-solving and communication skills",
    ],
    benefits: [
      "Competitive salary",
      "Remote work options",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development budget",

      "Flexible working hours",
    ],
    industry: "Data & Analytics",
    companyDescription:
      "DataInsights is a data analytics company that helps businesses make data-driven decisions through advanced analytics and machine learning.",
    companySize: "51-200 employees",
    founded: "2014",
    website: "www.datainsights.ai",
  },
  {
    id: "job6",
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Remote",
    type: "full-time",
    experience: "2-4 years",
    salary: "$100k - $130k",
    postedDate: "2 weeks ago",
    isRemote: true,
    isFeatured: false,
    isRecent: false,
    shortDescription: "Build and maintain our cloud infrastructure and CI/CD pipelines.",
    description:
      "We are seeking a DevOps Engineer to join our infrastructure team. You will be responsible for building and maintaining our cloud infrastructure, implementing CI/CD pipelines, and ensuring the reliability and security of our systems.",
    responsibilities: [
      "Build and maintain cloud infrastructure on AWS, GCP, or Azure",
      "Implement and maintain CI/CD pipelines",
      "Automate deployment processes",
      "Monitor system performance and troubleshoot issues",
      "Implement security best practices",
      "Collaborate with development teams to improve infrastructure",
    ],
    requirements: [
      "2-4 years of experience in DevOps or SRE roles",
      "Experience with cloud platforms (AWS, GCP, or Azure)",
      "Knowledge of infrastructure as code (Terraform, CloudFormation)",
      "Experience with containerization (Docker, Kubernetes)",
      "Understanding of CI/CD tools (Jenkins, GitHub Actions, CircleCI)",
      "Scripting skills (Bash, Python)",
    ],
    benefits: [
      "Competitive salary",
      "Remote work",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development budget",
      "Flexible working hours",
    ],
    industry: "Technology",
    companyDescription:
      "CloudTech is a cloud infrastructure company that helps businesses migrate to the cloud and optimize their cloud operations.",
    companySize: "51-200 employees",
    founded: "2016",
    website: "www.cloudtech.io",
  },
  {
    id: "job7",
    title: "Marketing Manager",
    company: "GrowthLabs",
    location: "Chicago, IL",
    type: "full-time",
    experience: "4-6 years",
    salary: "$90k - $120k",
    postedDate: "3 days ago",
    isRemote: false,
    isFeatured: false,
    isRecent: true,
    shortDescription: "Develop and execute marketing strategies to drive growth and brand awareness.",
    description:
      "We are looking for a Marketing Manager to join our team. You will be responsible for developing and executing marketing strategies, managing campaigns across various channels, and analyzing marketing performance to drive growth and brand awareness.",
    responsibilities: [
      "Develop and execute marketing strategies",
      "Manage campaigns across digital and traditional channels",
      "Create and manage content for website, social media, and email",
      "Analyze marketing performance and optimize campaigns",
      "Collaborate with sales, product, and design teams",
      "Manage marketing budget and resources",
    ],
    requirements: [
      "4-6 years of experience in marketing",
      "Experience with digital marketing channels",
      "Knowledge of marketing analytics tools",
      "Strong project management skills",
      "Excellent communication and writing skills",
      "Creative thinking and problem-solving abilities",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development opportunities",
      "Flexible working hours",
      "Company events and team building activities",
    ],
    industry: "Marketing",
    companyDescription:
      "GrowthLabs is a marketing agency that helps businesses grow through innovative marketing strategies and data-driven campaigns.",
    companySize: "51-200 employees",
    founded: "2015",
    website: "www.growthlabs.io",
  },
  {
    id: "job8",
    title: "Mobile Developer (iOS)",
    company: "AppWorks",
    location: "Los Angeles, CA",
    type: "full-time",
    experience: "2-4 years",
    salary: "$100k - $130k",
    postedDate: "1 week ago",
    isRemote: false,
    isFeatured: true,
    isRecent: false,
    shortDescription: "Build innovative iOS applications using Swift and modern development practices.",
    description:
      "We are seeking a talented iOS Developer to join our mobile team. You will be responsible for developing and maintaining iOS applications, implementing new features, and ensuring high-quality user experiences on Apple devices.",
    responsibilities: [
      "Develop and maintain iOS applications using Swift",
      "Implement new features and functionality",
      "Ensure high-quality user experiences on Apple devices",
      "Collaborate with designers and backend developers",
      "Write clean, maintainable, and efficient code",
      "Participate in code reviews and testing",
    ],
    requirements: [
      "2-4 years of experience in iOS development",
      "Strong proficiency in Swift",
      "Experience with iOS frameworks and APIs",
      "Knowledge of design patterns and software architecture",
      "Understanding of App Store submission process",
      "Experience with version control systems (Git)",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development budget",
      "Flexible working hours",
      "Company events and team building activities",
    ],
    industry: "Technology",
    companyDescription:
      "AppWorks is a mobile app development company that specializes in creating innovative and user-friendly applications for iOS and Android platforms.",
    companySize: "51-200 employees",
    founded: "2013",
    website: "www.appworks.io",
  },
  {
    id: "job9",
    title: "Customer Success Manager",
    company: "ClientFirst",
    location: "Denver, CO",
    type: "full-time",
    experience: "3-5 years",
    salary: "$80k - $100k",
    postedDate: "2 weeks ago",
    isRemote: true,
    isFeatured: false,
    isRecent: false,
    shortDescription: "Ensure customer satisfaction and drive retention by providing exceptional support and guidance.",
    description:
      "We are looking for a Customer Success Manager to join our team. You will be responsible for building and maintaining relationships with customers, ensuring their satisfaction with our products and services, and driving retention and growth.",
    responsibilities: [
      "Build and maintain relationships with customers",
      "Ensure customer satisfaction with our products and services",
      "Develop and implement customer success strategies",
      "Identify upsell and cross-sell opportunities",
      "Collaborate with sales, product, and support teams",
      "Monitor and analyze customer health metrics",
    ],
    requirements: [
      "3-5 years of experience in customer success or account management",
      "Strong communication and interpersonal skills",
      "Experience with CRM systems (Salesforce, HubSpot)",
      "Problem-solving abilities",
      "Understanding of SaaS business models",
      "Ability to build and maintain relationships with customers",
    ],
    benefits: [
      "Competitive salary",
      "Remote work options",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development opportunities",
      "Flexible working hours",
    ],
    industry: "Customer Success",
    companyDescription:
      "ClientFirst is a customer success platform that helps businesses improve customer satisfaction, reduce churn, and drive growth through data-driven insights and proactive engagement.",
    companySize: "51-200 employees",
    founded: "2014",
    website: "www.clientfirst.io",
  },
  {
    id: "job10",
    title: "Backend Developer (Node.js)",
    company: "ServerStack",
    location: "Remote",
    type: "contract",
    experience: "2-4 years",
    salary: "$70-$90/hour",
    postedDate: "4 days ago",
    isRemote: true,
    isFeatured: false,
    isRecent: true,
    shortDescription: "Develop robust backend services and APIs using Node.js and modern frameworks.",
    description:
      "We are seeking a Backend Developer with Node.js expertise to join our engineering team on a contract basis. You will be responsible for developing and maintaining backend services, designing and implementing APIs, and ensuring the scalability and performance of our systems.",
    responsibilities: [
      "Develop and maintain backend services using Node.js",
      "Design and implement RESTful APIs",
      "Ensure the scalability and performance of our systems",
      "Write clean, maintainable, and efficient code",
      "Collaborate with frontend developers and other team members",
      "Participate in code reviews and testing",
    ],
    requirements: [
      "2-4 years of experience in backend development",
      "Strong proficiency in Node.js and Express",
      "Experience with database systems (MongoDB, PostgreSQL)",
      "Knowledge of API design and development",
      "Understanding of security best practices",
      "Experience with version control systems (Git)",
    ],
    benefits: [
      "Competitive hourly rate",
      "Remote work",
      "Flexible working hours",
      "Opportunity for long-term collaboration",
      "Professional development opportunities",
      "Collaborative and supportive team environment",
    ],
    industry: "Technology",
    companyDescription:
      "ServerStack is a backend-as-a-service company that provides scalable and secure backend infrastructure for web and mobile applications.",
    companySize: "11-50 employees",
    founded: "2017",
    website: "www.serverstack.io",
  },
  {
    id: "job11",
    title: "HR Manager",
    company: "PeopleFirst",
    location: "Miami, FL",
    type: "full-time",
    experience: "5+ years",
    salary: "$90k - $120k",
    postedDate: "1 week ago",
    isRemote: false,
    isFeatured: false,
    isRecent: false,
    shortDescription: "Lead HR initiatives and foster a positive workplace culture in our growing organization.",
    description:
      "We are looking for an experienced HR Manager to join our team. You will be responsible for overseeing all HR functions, developing and implementing HR strategies, and fostering a positive workplace culture in our growing organization.",
    responsibilities: [
      "Oversee all HR functions (recruitment, onboarding, performance management, etc.)",
      "Develop and implement HR strategies and initiatives",
      "Foster a positive workplace culture",
      "Ensure compliance with employment laws and regulations",
      "Manage employee relations and resolve conflicts",
      "Develop and administer HR policies and procedures",
    ],
    requirements: [
      "5+ years of experience in HR management",
      "Knowledge of employment laws and regulations",
      "Experience with HRIS and ATS systems",
      "Strong leadership and interpersonal skills",
      "Excellent communication and conflict resolution abilities",
      "Bachelor's degree in HR, Business, or related field",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Professional development opportunities",
      "Flexible working hours",
      "Company events and team building activities",
    ],
    industry: "Human Resources",
    companyDescription:
      "PeopleFirst is an HR consulting firm that helps businesses attract, develop, and retain top talent through innovative HR strategies and solutions.",
    companySize: "51-200 employees",
    founded: "2012",
    website: "www.peoplefirst.io",
  },
  {
    id: "job12",
    title: "Content Writer",
    company: "ContentLab",
    location: "Remote",
    type: "part-time",
    experience: "1-3 years",
    salary: "$30-$50/hour",
    postedDate: "3 days ago",
    isRemote: true,
    isFeatured: false,
    isRecent: true,
    shortDescription: "Create engaging and informative content for various digital platforms.",
    description:
      "We are seeking a talented Content Writer to join our creative team on a part-time basis. You will be responsible for creating engaging and informative content for various digital platforms, including blogs, social media, and websites.",
    responsibilities: [
      "Create engaging and informative content for various digital platforms",
      "Research industry trends and topics",
      "Adhere to content guidelines and brand voice",
      "Edit and proofread content for accuracy and clarity",
      "Collaborate with marketing and design teams",
      "Meet deadlines and content calendar requirements",
    ],
    requirements: [
      "1-3 years of experience in content writing",
      "Strong writing and editing skills",
      "Knowledge of SEO best practices",
      "Ability to adapt writing style to different audiences",
      "Research and fact-checking abilities",
      "Portfolio of published work",
    ],
    benefits: [
      "Competitive hourly rate",
      "Remote work",
      "Flexible working hours",
      "Opportunity for long-term collaboration",
      "Professional development opportunities",
      "Exposure to various industries and topics",
    ],
    industry: "Content & Marketing",
    companyDescription:
      "ContentLab is a content marketing agency that helps businesses create high-quality content that engages audiences and drives results.",
    companySize: "11-50 employees",
    founded: "2018",
    website: "www.contentlab.io",
  },
]
